name: Test

on:
  pull_request:
  push:
    branches:
      - main
env:
  otp: "26.2.2"
  elixir: "1.16.1"
  MIX_ENV: test
  BUMBLEBEE_CACHE_DIR: ~/.cache/bumblebee

jobs:
  main:
    runs-on: ubuntu-latest

    services:
      db:
        image: pgvector/pgvector:pg16
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          elixir-version: ${{ env.elixir }}
          version-type: strict

      - name: Cache Mix
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.elixir }}-${{ env.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.elixir }}-${{ env.otp }}-

      - name: Cache Bumblebee models
        uses: actions/cache@v4
        with:
          path: ${{ env.BUMBLEBEE_CACHE_DIR }}
          key: ${{ runner.os }}-bumblebee

      - name: Install mix dependencies
        run: mix deps.get --check-locked

      - name: Compile dependencies
        run: mix deps.compile

      - name: Check formatting
        run: mix format --check-formatted

      - name: Check warnings
        run: mix compile --warnings-as-errors --force

      - name: Setup database
        run: mix do ecto.create, ecto.migrate

      - name: Run tests
        run: mix test --warnings-as-errors
